import React, { useState, useEffect } from 'react';

const legalContent = {
  terms: {
    title: "Terms & Conditions",
    content: (
      <div className="space-y-4">
        <p className="text-xs text-slate-400 italic">Last Updated: March 2026</p>
        <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
        <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <a href="https://backstage.events" className="text-teal-500 hover:underline">https://backstage.events</a> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').</p>
        <p>The Platform is owned by <strong>BACKSTAGE</strong>, a company incorporated under the Companies Act, 1956 (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').</p>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Use of Platform</h4>
        <ol className="list-decimal pl-5 space-y-2">
          <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration.</li>
          <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered.</li>
          <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable.</li>
          <li>The contents of the Platform and the Services are proprietary to us. You will not have any authority to claim any intellectual property rights.</li>
          <li>Unauthorized use of the Platform and/or the Services may lead to action against you.</li>
          <li>You agree to pay us the charges associated with availing the Services.</li>
          <li>You agree not to use the Platform for any purpose that is unlawful, illegal or forbidden.</li>
          <li>The Services may contain links to other third party websites. On accessing these links, you will be governed by their terms.</li>
          <li>You understand that upon initiating a transaction you are entering into a legally binding contract with the Platform Owner.</li>
          <li>You shall indemnify and hold harmless Platform Owner, its affiliates, and employees from any claim or demand arising out of your breach of these Terms.</li>
          <li>Parties shall not be liable for any failure to perform due to force majeure events.</li>
          <li>These Terms shall be governed by and construed in accordance with the laws of India.</li>
          <li>All disputes shall be subject to exclusive jurisdiction of the courts in Delhi.</li>
        </ol>
      </div>
    )
  },
  privacy: {
    title: "Privacy Policy",
    content: (
      <div className="space-y-4">
        <p>This Privacy Policy describes how BACKSTAGE and its affiliates collect, use, share, protect or otherwise process your information through our website <a href="https://backstage.events" className="text-teal-500 hover:underline">https://backstage.events</a>.</p>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Collection of Information</h4>
        <p>We collect your personal data when you use our Platform, services or otherwise interact with us. This includes name, date of birth, address, telephone number, email ID, and proof of identity. Sensitive personal data, such as bank account or payment instrument information, may be collected with your consent to enable specific features.</p>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Usage of Data</h4>
        <p>We use personal data to provide the services you request, market to you (with opt-out ability), assist sellers in fulfilling orders, resolve disputes, and customize your experience.</p>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Sharing of Data</h4>
        <p>We may share your data within our group entities and with third-party service providers (logistics, payment issuers) to fulfill your requests and comply with legal obligations.</p>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Security</h4>
        <p>We adopt reasonable security practices and procedures to protect your data. However, the transmission of information over the internet is not completely secure beyond our control.</p>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Withdrawal of Consent</h4>
        <p>You have an option to withdraw your consent by writing to our Grievance Officer. However, this may restrict your access to certain services.</p>
      </div>
    )
  },
  refunds: {
    title: "Refunds & Cancellation",
    content: (
      <div className="space-y-4">
        <h4 className="text-lg font-bold text-slate-800 mt-6">Cancellation Policy</h4>
        <ul className="list-disc pl-5 space-y-2">
          <li>Cancellations will only be considered if request is made 1 day of placing the order.</li>
          <li>Requests may not be entertained if the order has been communicated to sellers and they have initiated shipping.</li>
          <li>Cancellation for perishable items like flowers/eatables is not accepted unless quality issues are established.</li>
        </ul>
        <h4 className="text-lg font-bold text-slate-800 mt-6">Refunds & Returns</h4>
        <p>We offer return/exchange within 1 day from the date of purchase. Item must be unused, in original packaging, and not from a sale category.</p>
        <p>Once approved after quality check, your refund will take approx 6 days to be processed.</p>
        <p>Damaged or defective items should be reported within 1 day of receipt.</p>
      </div>
    )
  },
  shipping: {
    title: "Shipping Policy",
    content: (
      <div className="space-y-4">
        <p>Orders are shipped through registered domestic courier companies and/or speed post only.</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Orders are shipped within 5 days from the date of order/payment.</li>
          <li>Platform Owner is not liable for any delay in delivery by the courier company or postal authority.</li>
          <li>Delivery will be made to the address provided by the buyer.</li>
          <li>Delivery of services will be confirmed via your registered email ID.</li>
          <li>Shipping costs levied by the seller/platform are generally non-refundable.</li>
        </ul>
      </div>
    )
  }
};

const LegalModal = ({ isOpen, onClose, initialTab = 'terms' }) => {
  const [activeTab, setActiveTab] = useState(initialTab);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      setActiveTab(initialTab);
    } else {
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [isOpen, initialTab]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 md:p-10 animate-in fade-in duration-300">
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-md" onClick={onClose}></div>
      <div className="relative bg-white w-full max-w-4xl h-full max-h-[85vh] rounded-[2rem] shadow-2xl overflow-hidden flex flex-col md:flex-row animate-in zoom-in-95 duration-300">
        {/* Sidebar Nav */}
        <div className="w-full md:w-64 bg-slate-50 border-r border-slate-100 p-8 flex flex-col">
          <div className="flex items-center gap-3 mb-10">
            <img src="/favicon.png" className="h-8 w-8 rounded-lg shadow-sm" alt="Logo" onError={(e) => e.target.src = './favicon.png'} />
            <span className="font-bold text-slate-900 tracking-tight">Legal Center</span>
          </div>
          <nav className="space-y-2 flex-1">
            {Object.keys(legalContent).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`w-full text-left px-4 py-3 rounded-xl text-sm transition-all ${
                  activeTab === tab
                    ? 'font-bold bg-white text-teal-600 shadow-sm ring-1 ring-slate-100'
                    : 'font-semibold text-slate-500 hover:bg-white hover:text-slate-900'
                }`}
              >
                {legalContent[tab].title}
              </button>
            ))}
          </nav>
          <button
            onClick={onClose}
            className="mt-8 w-full bg-slate-900 text-white py-3 rounded-xl text-sm font-bold shadow-lg hover:bg-slate-800 transition-all text-center"
          >
            Close
          </button>
        </div>
        {/* Content Area */}
        <div className="flex-1 flex flex-col min-w-0 bg-white">
          <div className="p-8 border-b border-slate-50 flex justify-between items-center">
            <h2 className="text-2xl font-black text-slate-900 uppercase">{legalContent[activeTab].title}</h2>
            <button onClick={onClose} className="text-slate-400 hover:text-slate-900 transition-colors p-2">
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>
          </div>
          <div className="p-8 overflow-y-auto flex-1 text-slate-600 text-sm leading-relaxed scroll-smooth">
            {legalContent[activeTab].content}
          </div>
        </div>
      </div>
    </div>
  );
};

export default LegalModal;
